-- AlterTable
ALTER TABLE "Repeat" ALTER COLUMN "months" SET DEFAULT ARRAY[]::INTEGER[],
ALTER COLUMN "daysOfMonth" SET DEFAULT ARRAY[]::INTEGER[],
ALTER COLUMN "daysOfWeek" SET DEFAULT ARRAY[]::INTEGER[];
